import React, { useState, useEffect } from 'react';
import { Student, NLPCDetail, NLPCTemplate } from '../types';
import { Sparkles, Download, CheckSquare, UserCheck, Library, RefreshCw, Copy, GraduationCap, Plus, Trash2 } from 'lucide-react';
import { utils, writeFile } from 'xlsx';

interface Props {
  students: Student[];
  onGenerate: () => void;
  isProcessing: boolean;
  onUpdateLevel: (studentId: string, category: 'nlChung'|'nlDacThu'|'phamChat'|'hbs', level: 'Tốt'|'Đạt'|'CCG') => void;
  onUpdateComment: (studentId: string, category: 'nlChung'|'nlDacThu'|'phamChat'|'hbs', content: string) => void;
  onBulkUpdateLevel: (category: 'nlChung'|'nlDacThu'|'phamChat'|'hbs', level: 'Tốt'|'Đạt'|'CCG') => void;
  onRegenerateSingle: (studentId: string, category: 'nlChung'|'nlDacThu'|'phamChat'|'hbs') => void; 
  selectedGrade: number;
  nlpcTemplates: NLPCTemplate[];
  onAddTemplate?: (category: string, level: string, content: string) => void; // NEW
  onDeleteTemplate?: (category: string, level: string, content: string) => void; // NEW
}

const LevelSelector: React.FC<{
    value: string;
    onChange: (val: any) => void;
    size?: 'sm' | 'xs';
    customLabels?: Record<string, string>;
}> = ({ value, onChange, size = 'xs', customLabels }) => {
    const getColor = (v: string) => {
        if (v === 'Tốt') return 'bg-green-100 text-green-800 border-green-200';
        if (v === 'Đạt') return 'bg-blue-100 text-blue-800 border-blue-200';
        return 'bg-red-100 text-red-800 border-red-200';
    };

    const py = size === 'sm' ? 'py-1' : 'py-0.5';

    return (
        <select 
            value={value} 
            onChange={(e) => onChange(e.target.value)}
            className={`text-[10px] font-bold border rounded px-1 ${py} cursor-pointer outline-none ${getColor(value)}`}
        >
            <option value="Tốt">{customLabels ? customLabels['Tốt'] : 'Tốt'}</option>
            <option value="Đạt">{customLabels ? customLabels['Đạt'] : 'Đạt'}</option>
            <option value="CCG">{customLabels ? customLabels['CCG'] : 'CCG'}</option>
        </select>
    );
};

// --- MEMOIZED TEXTAREA COMPONENT (Local State Sync) ---
const NLPCTextArea = ({ 
    defaultValue, 
    onSave 
}: { 
    defaultValue: string, 
    onSave: (val: string) => void 
}) => {
    const [localVal, setLocalVal] = useState(defaultValue);

    // Sync when props change (e.g. Generated by button)
    useEffect(() => {
        setLocalVal(defaultValue);
    }, [defaultValue]);

    const handleBlur = () => {
        if (localVal !== defaultValue) {
            onSave(localVal);
        }
    };

    return (
        <textarea 
            className="w-full text-xs border-gray-200 rounded p-2 bg-gray-50 focus:bg-white focus:ring-1 focus:ring-blue-500 min-h-[60px] resize-none"
            value={localVal}
            onChange={(e) => setLocalVal(e.target.value)}
            onBlur={handleBlur}
            placeholder={`Nhận xét...`}
        />
    );
};

// --- MEMOIZED ROW COMPONENT ---
interface NLPCRowProps {
    index: number;
    student: Student;
    onUpdateLevel: (studentId: string, category: 'nlChung'|'nlDacThu'|'phamChat'|'hbs', level: 'Tốt'|'Đạt'|'CCG') => void;
    onUpdateComment: (studentId: string, category: 'nlChung'|'nlDacThu'|'phamChat'|'hbs', content: string) => void;
    onRegenerateSingle: (studentId: string, category: 'nlChung'|'nlDacThu'|'phamChat'|'hbs') => void;
}

const NLPCRow = React.memo(({ index, student, onUpdateLevel, onUpdateComment, onRegenerateSingle }: NLPCRowProps) => {
    const levels = student.nlpcLevels || { nlChung: 'Đạt', nlDacThu: 'Đạt', phamChat: 'Đạt', hbs: 'Đạt', hbsRaw: '' };
    const details = student.nlpcLevels?.details;

    const renderCellContent = (category: 'nlChung'|'nlDacThu'|'phamChat'|'hbs', comment: string | undefined) => {
        const hasDetails = category !== 'hbs' && details && details[category] && details[category].length > 0;
        
        return (
            <td className="px-3 py-3 align-top border-l border-gray-100 group/cell relative">
            <div className="flex flex-col gap-2 mb-2">
                <div className="flex justify-between items-center bg-gray-50 p-1.5 rounded border border-gray-200">
                    {category === 'hbs' && levels.hbsRaw ? (
                            <div className="flex-1 mr-2 overflow-hidden">
                                <span className="text-[10px] text-gray-400 block leading-tight mb-0.5">Đánh giá:</span>
                                <div className="flex flex-col">
                                    <span className={`text-xs font-bold truncate block ${
                                        levels.hbs === 'Tốt' ? 'text-green-700' : 
                                        levels.hbs === 'CCG' ? 'text-red-700' : 'text-blue-700'
                                    }`}>
                                        {levels.hbs}
                                    </span>
                                    {levels.hbsRaw && levels.hbsRaw.toUpperCase() !== levels.hbs.toUpperCase() && (
                                         <span className="text-[9px] text-gray-500 font-normal truncate" title={levels.hbsRaw}>
                                            ({levels.hbsRaw})
                                         </span>
                                    )}
                                </div>
                            </div>
                    ) : (
                            <span className="text-xs font-bold text-gray-600">Đánh giá:</span>
                    )}
                    
                    <div className="flex items-center gap-1 shrink-0">
                        <LevelSelector 
                            value={levels[category]} 
                            onChange={(val) => onUpdateLevel(student.id, category, val)}
                            size="sm"
                        />
                        <button 
                            onClick={() => onRegenerateSingle(student.id, category)}
                            title="Lấy câu khác từ mẫu"
                            className="p-1 hover:bg-blue-100 rounded text-blue-600 transition-colors"
                        >
                            <RefreshCw size={12} />
                        </button>
                    </div>
                </div>

                {hasDetails && (
                    <div className="flex flex-col gap-1 mt-1">
                        {details[category].map((d: any, i: any) => (
                            <div key={i} className="flex items-center justify-between text-[10px] bg-white border border-gray-100 rounded px-2 py-1.5">
                                <span className="text-gray-600 font-medium" title={d.name}>{d.name}</span>
                                <span className={`font-bold ml-1 ${d.level === 'Tốt' ? 'text-green-600' : d.level === 'CCG' ? 'text-red-500' : 'text-blue-600'}`}>
                                    {d.level}
                                </span>
                            </div>
                        ))}
                    </div>
                )}
            </div>

            <NLPCTextArea 
                defaultValue={comment || ""}
                onSave={(val) => onUpdateComment(student.id, category, val)}
            />
            </td>
        );
    };

    return (
        <tr className="hover:bg-gray-50 group transition-colors">
            <td className="px-4 py-4 whitespace-nowrap text-sm text-gray-500 align-top">{index + 1}</td>
            <td className="px-4 py-4 whitespace-nowrap text-sm font-medium text-gray-900 align-top">
                <div className="whitespace-normal">{student.name}</div>
                <div className="text-[10px] text-gray-400 font-mono mt-1">{student.studentCode}</div>
            </td>
            
            {renderCellContent('nlChung', student.commentNLChung)}
            {renderCellContent('nlDacThu', student.commentNLDacThu)}
            {renderCellContent('phamChat', student.commentPhamChat)}
            {renderCellContent('hbs', student.commentHBS)}
        </tr>
    );
}, (prev, next) => {
    return prev.student === next.student && prev.index === next.index;
});
// ------------------------------

export const ModuleNLPC: React.FC<Props> = ({ 
    students, onGenerate, isProcessing, onUpdateLevel, onUpdateComment, onBulkUpdateLevel, onRegenerateSingle,
    selectedGrade, nlpcTemplates, onAddTemplate, onDeleteTemplate
}) => {
  const [showLibrary, setShowLibrary] = useState(false);
  const [copiedText, setCopiedText] = useState<string | null>(null);
  
  // NEW: State for adding template
  const [newCat, setNewCat] = useState('NL_CHUNG');
  const [newLvl, setNewLvl] = useState('Tốt');
  const [newContent, setNewContent] = useState('');

  if (students.length === 0) return <div className="p-8 text-center text-gray-500">Vui lòng upload dữ liệu học sinh trước.</div>;

  const handleExportWord = () => {
      const exportData = students.map((s, idx) => ({
          STT: idx + 1,
          MaHS: s.studentCode,
          HoTen: s.name,
          NangLucChung: s.commentNLChung,
          NangLucDacThu: s.commentNLDacThu,
          PhamChat: s.commentPhamChat,
          NhanXetHocBaSo: s.commentHBS
      }));
      const ws = utils.json_to_sheet(exportData);
      const wb = utils.book_new();
      utils.book_append_sheet(wb, ws, "NLPC");
      writeFile(wb, "NhanXet_NLPC_HBS.xlsx");
  };

  const handleCopyTemplate = (text: string) => {
      navigator.clipboard.writeText(text);
      setCopiedText(text);
      setTimeout(() => setCopiedText(null), 2000);
  };
  
  const handleAddNew = () => {
      if (!newContent.trim() || !onAddTemplate) return;
      onAddTemplate(newCat, newLvl, newContent.trim());
      setNewContent('');
  };

  const getTemplates = (category: 'NL_CHUNG' | 'NL_DACTHU' | 'PHAM_CHAT' | 'HBS', level: 'Tốt'|'Đạt'|'CCG') => {
      let matches = nlpcTemplates.filter(t => t.gradeLevel === selectedGrade && t.category === category && t.level === level);
      if (matches.length === 0) {
          matches = nlpcTemplates.filter(t => t.gradeLevel === 4 && t.category === category && t.level === level);
      }
      return matches.flatMap(t => t.templates);
  };

  return (
    <div className="h-full flex flex-col md:flex-row gap-4 overflow-hidden">
      <div className="flex-1 flex flex-col min-w-0">
        <div className="mb-4 flex flex-col lg:flex-row justify-between items-start lg:items-center gap-4 bg-white p-4 rounded-lg border border-gray-200 shadow-sm shrink-0">
            <div>
            <h2 className="text-xl font-bold text-gray-800 flex items-center gap-2">
                <UserCheck className="text-pink-600"/>
                Năng Lực & Phẩm Chất
            </h2>
            <p className="text-xs text-gray-500 mt-1">Khối {selectedGrade} - Chọn mức độ và tạo nhận xét từ bộ mẫu.</p>
            </div>
            
            <div className="flex flex-wrap gap-2 items-center">
                <div className="flex items-center gap-1 text-xs text-gray-600 bg-gray-50 px-2 py-1 rounded border mr-2">
                    <CheckSquare size={14}/>
                    <span className="font-semibold">Điền nhanh:</span>
                    <button onClick={() => onBulkUpdateLevel('nlChung', 'Tốt')} className="hover:text-green-600 hover:underline">NL Chung(Tốt)</button>
                    <span className="text-gray-300">|</span>
                    <button onClick={() => onBulkUpdateLevel('nlDacThu', 'Tốt')} className="hover:text-green-600 hover:underline">Đặc Thù(Tốt)</button>
                    <span className="text-gray-300">|</span>
                    <button onClick={() => onBulkUpdateLevel('phamChat', 'Tốt')} className="hover:text-green-600 hover:underline">P.Chất(Tốt)</button>
                    <span className="text-gray-300">|</span>
                    <button onClick={() => onBulkUpdateLevel('hbs', 'Tốt')} className="hover:text-green-600 hover:underline">HBS(Tốt)</button>
                </div>

            <button
                onClick={() => setShowLibrary(!showLibrary)}
                className={`flex items-center gap-2 px-3 py-2 rounded-md text-sm transition-colors mr-2 ${showLibrary ? 'bg-blue-100 text-blue-700 font-medium' : 'bg-gray-100 text-gray-600 hover:bg-gray-200'}`}
            >
                <Library size={16} />
                <span className="hidden lg:inline">Thư viện mẫu</span>
            </button>

            <button
                onClick={onGenerate}
                disabled={isProcessing}
                className={`flex items-center gap-2 px-4 py-2 rounded-md text-white transition-all text-sm font-medium ${isProcessing ? 'bg-gray-400 cursor-not-allowed' : 'bg-pink-600 hover:bg-pink-700 shadow-md'}`}
            >
                <Sparkles size={16} className={isProcessing ? "animate-spin" : ""} />
                {isProcessing ? "Đang tạo..." : "Tạo Tất Cả"}
            </button>
            
            <button 
                    onClick={handleExportWord}
                    className="flex items-center gap-2 px-4 py-2 border border-green-600 text-green-700 rounded-md hover:bg-green-50 transition-colors text-sm font-medium"
                >
                <Download size={16} /> Xuất Excel
            </button>
            </div>
        </div>

        <div className="flex-1 overflow-auto bg-white rounded-lg shadow border border-gray-200">
            <table className="min-w-full divide-y divide-gray-200 table-fixed">
            <thead className="bg-gray-50 sticky top-0 z-10 shadow-sm">
                <tr>
                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-12 border-b">STT</th>
                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-40 border-b">Họ Tên</th>
                
                <th className="px-3 py-3 text-left text-xs font-medium text-blue-700 uppercase tracking-wider border-b border-l border-gray-200 bg-blue-50/50">
                    Năng Lực Chung
                </th>
                
                <th className="px-3 py-3 text-left text-xs font-medium text-indigo-700 uppercase tracking-wider border-b border-l border-gray-200 bg-indigo-50/50">
                    Năng Lực Đặc Thù
                </th>

                <th className="px-3 py-3 text-left text-xs font-medium text-pink-700 uppercase tracking-wider border-b border-l border-gray-200 bg-pink-50/50">
                    Phẩm Chất
                </th>

                <th className="px-3 py-3 text-left text-xs font-medium text-teal-700 uppercase tracking-wider border-b border-l border-gray-200 bg-teal-50/50">
                    Nhận xét HBS
                </th>
                </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
                {students.map((student, idx) => (
                    <NLPCRow 
                        key={student.id}
                        index={idx}
                        student={student}
                        onUpdateLevel={onUpdateLevel}
                        onUpdateComment={onUpdateComment}
                        onRegenerateSingle={onRegenerateSingle}
                    />
                ))}
            </tbody>
            </table>
        </div>
      </div>

      {showLibrary && (
          <div className="w-80 bg-gray-50 border-l border-gray-200 flex flex-col shrink-0 shadow-inner h-full overflow-hidden">
             <div className="p-3 border-b border-gray-200 bg-white sticky top-0 z-10">
                <h4 className="font-bold text-gray-700 text-sm flex items-center gap-2">
                    <Library size={14}/> Thư viện mẫu (Khối {selectedGrade})
                </h4>
                <p className="text-[10px] text-gray-400 mt-1">Bấm vào câu mẫu để sao chép.</p>
             </div>
             
             {/* NEW: Add Template Form */}
             {onAddTemplate && (
                 <div className="p-3 bg-blue-50 border-b border-blue-100">
                      <h5 className="text-xs font-bold text-blue-700 mb-2 flex items-center gap-1">
                         <Plus size={12}/> Thêm mẫu mới
                      </h5>
                      <div className="space-y-2">
                         <div className="flex gap-1">
                            <select 
                                className="flex-1 text-xs p-1.5 border border-blue-200 rounded focus:ring-1 focus:ring-blue-500 bg-white"
                                value={newCat}
                                onChange={(e) => setNewCat(e.target.value)}
                            >
                                <option value="NL_CHUNG">Năng lực chung</option>
                                <option value="NL_DACTHU">NL Đặc thù</option>
                                <option value="PHAM_CHAT">Phẩm chất</option>
                                <option value="HBS">Học bạ số</option>
                            </select>
                            <select 
                                className="w-20 text-xs p-1.5 border border-blue-200 rounded focus:ring-1 focus:ring-blue-500 bg-white"
                                value={newLvl}
                                onChange={(e) => setNewLvl(e.target.value)}
                            >
                                <option value="Tốt">Tốt</option>
                                <option value="Đạt">Đạt</option>
                                <option value="CCG">CCG</option>
                            </select>
                         </div>
                         
                         <textarea 
                             className="w-full text-xs p-2 border border-blue-200 rounded focus:ring-1 focus:ring-blue-500 min-h-[50px] resize-y"
                             placeholder="Nhập nội dung mẫu câu (Mỗi câu một dòng)..."
                             value={newContent}
                             onChange={(e) => setNewContent(e.target.value)}
                         />
                         <button 
                             onClick={handleAddNew}
                             disabled={!newContent.trim()}
                             className="w-full bg-blue-600 hover:bg-blue-700 text-white text-xs font-medium py-1.5 rounded disabled:opacity-50"
                         >
                             Lưu tất cả mẫu này
                         </button>
                      </div>
                 </div>
             )}

             <div className="flex-1 overflow-y-auto p-3 space-y-6">
                
                {/* SECTION: NL CHUNG */}
                <div>
                   <h5 className="text-xs font-bold text-blue-700 uppercase mb-2 border-b border-blue-200 pb-1">1. Năng Lực Chung</h5>
                   <div className="space-y-3">
                      {['Tốt', 'Đạt', 'CCG'].map((lvl: any) => (
                          <div key={lvl}>
                             <div className="text-[10px] font-bold text-gray-500 mb-1">Mức: {lvl}</div>
                             <ul className="text-xs text-gray-600 space-y-1 list-none">
                                {getTemplates('NL_CHUNG', lvl).map((t, i) => (
                                    <li 
                                        key={i} 
                                        onClick={() => handleCopyTemplate(t)}
                                        className={`p-2 rounded border border-gray-100 mb-1 cursor-pointer transition-colors relative group ${copiedText === t ? 'bg-green-50 border-green-200 text-green-700' : 'bg-white hover:bg-blue-50 hover:border-blue-200'}`}
                                    >
                                        <div className="pr-4">{t}</div>
                                        <div className="absolute right-1 top-1 flex flex-col gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                                            <div className="p-1 text-gray-400 bg-white/80 rounded hover:text-blue-600">
                                                <Copy size={12} />
                                            </div>
                                            {onDeleteTemplate && (
                                                <button 
                                                    onClick={(e) => {
                                                        e.stopPropagation();
                                                        onDeleteTemplate('NL_CHUNG', lvl, t);
                                                    }}
                                                    className="p-1 text-gray-400 bg-white/80 rounded hover:text-red-600"
                                                    title="Xóa"
                                                >
                                                    <Trash2 size={12} />
                                                </button>
                                            )}
                                        </div>
                                    </li>
                                ))}
                             </ul>
                          </div>
                      ))}
                   </div>
                </div>

                {/* SECTION: NL DAC THU */}
                <div>
                   <h5 className="text-xs font-bold text-indigo-700 uppercase mb-2 border-b border-indigo-200 pb-1">2. Năng Lực Đặc Thù</h5>
                   <div className="space-y-3">
                      {['Tốt', 'Đạt', 'CCG'].map((lvl: any) => (
                          <div key={lvl}>
                             <div className="text-[10px] font-bold text-gray-500 mb-1">Mức: {lvl}</div>
                             <ul className="text-xs text-gray-600 space-y-1 list-none">
                                {getTemplates('NL_DACTHU', lvl).map((t, i) => (
                                    <li 
                                        key={i} 
                                        onClick={() => handleCopyTemplate(t)}
                                        className={`p-2 rounded border border-gray-100 mb-1 cursor-pointer transition-colors relative group ${copiedText === t ? 'bg-green-50 border-green-200 text-green-700' : 'bg-white hover:bg-indigo-50 hover:border-indigo-200'}`}
                                    >
                                        <div className="pr-4">{t}</div>
                                        <div className="absolute right-1 top-1 flex flex-col gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                                            <div className="p-1 text-gray-400 bg-white/80 rounded hover:text-blue-600">
                                                <Copy size={12} />
                                            </div>
                                            {onDeleteTemplate && (
                                                <button 
                                                    onClick={(e) => {
                                                        e.stopPropagation();
                                                        onDeleteTemplate('NL_DACTHU', lvl, t);
                                                    }}
                                                    className="p-1 text-gray-400 bg-white/80 rounded hover:text-red-600"
                                                    title="Xóa"
                                                >
                                                    <Trash2 size={12} />
                                                </button>
                                            )}
                                        </div>
                                    </li>
                                ))}
                             </ul>
                          </div>
                      ))}
                   </div>
                </div>

                {/* SECTION: PHAM CHAT */}
                <div>
                   <h5 className="text-xs font-bold text-pink-700 uppercase mb-2 border-b border-pink-200 pb-1">3. Phẩm Chất</h5>
                   <div className="space-y-3">
                      {['Tốt', 'Đạt', 'CCG'].map((lvl: any) => (
                          <div key={lvl}>
                             <div className="text-[10px] font-bold text-gray-500 mb-1">Mức: {lvl}</div>
                             <ul className="text-xs text-gray-600 space-y-1 list-none">
                                {getTemplates('PHAM_CHAT', lvl).map((t, i) => (
                                    <li 
                                        key={i} 
                                        onClick={() => handleCopyTemplate(t)}
                                        className={`p-2 rounded border border-gray-100 mb-1 cursor-pointer transition-colors relative group ${copiedText === t ? 'bg-green-50 border-green-200 text-green-700' : 'bg-white hover:bg-pink-50 hover:border-pink-200'}`}
                                    >
                                        <div className="pr-4">{t}</div>
                                        <div className="absolute right-1 top-1 flex flex-col gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                                            <div className="p-1 text-gray-400 bg-white/80 rounded hover:text-blue-600">
                                                <Copy size={12} />
                                            </div>
                                            {onDeleteTemplate && (
                                                <button 
                                                    onClick={(e) => {
                                                        e.stopPropagation();
                                                        onDeleteTemplate('PHAM_CHAT', lvl, t);
                                                    }}
                                                    className="p-1 text-gray-400 bg-white/80 rounded hover:text-red-600"
                                                    title="Xóa"
                                                >
                                                    <Trash2 size={12} />
                                                </button>
                                            )}
                                        </div>
                                    </li>
                                ))}
                             </ul>
                          </div>
                      ))}
                   </div>
                </div>

                {/* SECTION: HOC BA SO */}
                <div>
                   <h5 className="text-xs font-bold text-teal-700 uppercase mb-2 border-b border-teal-200 pb-1 flex items-center gap-1">
                      <GraduationCap size={14}/> 4. Nhận xét HBS
                   </h5>
                   <div className="space-y-3">
                      {['Tốt', 'Đạt', 'CCG'].map((lvl: any) => (
                          <div key={lvl}>
                             <div className="text-[10px] font-bold text-gray-500 mb-1">Mức: {lvl}</div>
                             <ul className="text-xs text-gray-600 space-y-1 list-none">
                                {getTemplates('HBS', lvl).map((t, i) => (
                                    <li 
                                        key={i} 
                                        onClick={() => handleCopyTemplate(t)}
                                        className={`p-2 rounded border border-gray-100 mb-1 cursor-pointer transition-colors relative group ${copiedText === t ? 'bg-green-50 border-green-200 text-green-700' : 'bg-white hover:bg-teal-50 hover:border-teal-200'}`}
                                    >
                                        <div className="pr-4">{t}</div>
                                        <div className="absolute right-1 top-1 flex flex-col gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                                            <div className="p-1 text-gray-400 bg-white/80 rounded hover:text-blue-600">
                                                <Copy size={12} />
                                            </div>
                                            {onDeleteTemplate && (
                                                <button 
                                                    onClick={(e) => {
                                                        e.stopPropagation();
                                                        onDeleteTemplate('HBS', lvl, t);
                                                    }}
                                                    className="p-1 text-gray-400 bg-white/80 rounded hover:text-red-600"
                                                    title="Xóa"
                                                >
                                                    <Trash2 size={12} />
                                                </button>
                                            )}
                                        </div>
                                    </li>
                                ))}
                             </ul>
                          </div>
                      ))}
                   </div>
                </div>

             </div>
          </div>
      )}
    </div>
  );
};